services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - LLAMA_API_URL=http://localhost:8000/v1/chat/completions
      - IMAGE_ANALYSIS_API_URL=http://localhost:8002/v1/analyze

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - REACT_APP_IMAGE_ANALYSIS_API_URL=http://localhost:8002
