services:
  llama:
    image: nvcr.io/nim/meta/llama-3.2-90b-vision-instruct:1.1.1
    environment:
      - NGC_API_KEY=${NGC_API_KEY}
    volumes:
      - ${LOCAL_NIM_CACHE:-~/.cache/nim}:/opt/nim/.cache
    ports:
      - "8000:8000"
    shm_size: '16gb'

  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - llama
    environment:
      - LLAMA_API_URL=http://llama:8000/v1/chat/completions
      - IMAGE_ANALYSIS_API_URL=http://image-analysis:8002/v1/analyze

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - REACT_APP_IMAGE_ANALYSIS_API_URL=http://localhost:8002
